// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "node:fs";
import path from "node:path";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

const envCandidates = [
  process.env.DOTENV_CONFIG_PATH,
  path.resolve(process.cwd(), ".env"),
  path.resolve(process.cwd(), ".env.development"),
].filter((value): value is string => Boolean(value));

for (const envPath of envCandidates) {
  if (fs.existsSync(envPath)) {
    loadEnv({ path: envPath });
    break;
  }
}

const databaseUrl = process.env.DATABASE_URL?.trim() || "file:./prisma/dev.db";

const normalizeDatabaseUrl = (url: string): string => {
  const trimmed = url.trim();
  if (trimmed === ":memory:") {
    return trimmed;
  }
  if (trimmed.startsWith("file:")) {
    const pathPart = trimmed.slice("file:".length);
    if (!pathPart || pathPart === ":memory:") {
      return ":memory:";
    }
    if (path.isAbsolute(pathPart)) {
      return trimmed;
    }
    return `file:${path.resolve(process.cwd(), pathPart)}`;
  }
  if (/^[a-z][a-z0-9+.-]*:/.test(trimmed)) {
    return trimmed;
  }
  return `file:${path.resolve(process.cwd(), trimmed)}`;
};

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: normalizeDatabaseUrl(databaseUrl),
  },
});
